### ISSUE TITLE
Parameter maunalCutOff is never used

### ISSUE THREAD

**Issue by maguirreg** [lvlegab1te/Fan-Manager#1]
Background:
If the average temperature is greater than a certain value, then the automatic fan control should be disabled.

Issue:
Parameter `maunalCutOff` is never used, the Max Temp to use automatic fan control is set to `60` regardless of this setting.
Delcared in:
```
pollInterval = 5                    # in seconds
maunalCutOff = 60                   # Max Temp before manual control is disabled 
daily_list = []                     # length =  86400 / pollinterval
```

Expected Behaviour:
The parameter `maunalCutOff` should be used when checking max temp to disable automatic fan managing.
```
        if(t > 60): # maunalCutOff could be used here
            log.write("Temp too high! Disabling Manual Fan Control\n")
            FanControlSwitch(False)
```

Proposed:
A custom configuration file could be used to load parameters and override the default ones

**Comment by lvlegab1te** [comment]
A mechanism for loading and managing configuration files is being worked on and will resolve this issue when implemented
